name: Message Rendering

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  message_rendering:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: false

    name: Linux / PHP 8.3

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Run via docker compose because we can't run greenmail in a server here
      # (it requires the testing emails to be present when starting but
      # services are started before the repo is cloned). And instead of
      # re-building what our compose-file contains we can just use it.
      - name: Run tests via docker compose
        run: docker compose -f .ci/compose.yaml run test_message_rendering

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: failure()
        with:
          name: Logs
          path: logs/errors.log

